name: "demo actions"
on: 
    push:
jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v4
            
            - name: Install cowsay
              run: sudo apt-get install cowsay -y
            
            - name: cowsay
              run: cowsay -f moose "Run for cover I am a dragon ... RAWWW" >> lion.txt

            - name: display
              run: cat lion.txt